# Generated by Django 4.2.16 on 2024-09-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_saveorder_saveorderproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveorderproduct',
            name='color',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='saveorderproduct',
            name='size',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
